# Generated by Django 4.2.4 on 2023-09-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Category_Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Category_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categories'),
            preserve_default=False,
        ),
    ]
