# Generated by Django 4.1.10 on 2023-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('contect_add', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
            ],
        ),
    ]
